# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QztDb4mq_1dxJCiPMm53WudVulOacnpN
"""

!pip install brian2 --quiet
from brian2 import *
import matplotlib.pyplot as plt

# Set global parameters
tau = 10*ms
V_reset = 0

# =============================================================================
# 1. AND Gate Implementation
# =============================================================================
def simulate_AND():
    print("\nAND Gate Results:")
    V_th = 1.5  # Threshold
    w = 1.0      # Synaptic weights

    for A, B in [(0,0), (0,1), (1,0), (1,1)]:
        start_scope()
        eqs = '''
        dv/dt = (I - v)/tau : 1
        I : 1
        '''
        neuron = NeuronGroup(1, eqs, threshold='v > V_th', reset='v = V_reset', method='exact')
        neuron.I = w*A + w*B
        spike_mon = SpikeMonitor(neuron)
        run(20*ms)
        print(f"Input ({A},{B}) → Output: {1 if spike_mon.count[0] > 0 else 0}")

# =============================================================================
# 2. OR Gate Implementation
# =============================================================================
def simulate_OR():
    print("\nOR Gate Results:")
    V_th = 0.8  # Lower threshold
    w = 1.0

    for A, B in [(0,0), (0,1), (1,0), (1,1)]:
        start_scope()
        eqs = '''
        dv/dt = (I - v)/tau : 1
        I : 1
        '''
        neuron = NeuronGroup(1, eqs, threshold='v > V_th', reset='v = V_reset', method='exact')
        neuron.I = w*A + w*B
        spike_mon = SpikeMonitor(neuron)
        run(20*ms)
        print(f"Input ({A},{B}) → Output: {1 if spike_mon.count[0] > 0 else 0}")

# =============================================================================
# 3. NOT Gate Implementation
# =============================================================================
def simulate_NOT():
    print("\nNOT Gate Results:")
    V_th = 0.5
    w = -1.0  # Inhibitory weight
    bias = 1.0

    for A in [0, 1]:
        start_scope()
        eqs = '''
        dv/dt = (I - v)/tau : 1
        I : 1
        '''
        neuron = NeuronGroup(1, eqs, threshold='v > V_th', reset='v = V_reset', method='exact')
        neuron.I = w*A + bias
        spike_mon = SpikeMonitor(neuron)
        run(20*ms)
        print(f"Input {A} → Output: {1 if spike_mon.count[0] > 0 else 0}")

# =============================================================================
# 4. XOR Gate Implementation (Two-Layer Network)
# =============================================================================
def simulate_XOR():
    print("\nXOR Gate Results:")

    # First layer parameters
    V_th_layer1 = 1.0
    weights_layer1 = [(1.5, -1.0), (-1.0, 1.5)]  # (A∧¬B) and (¬A∧B)

    # Second layer (OR gate)
    V_th_layer2 = 0.9

    for A, B in [(0,0), (0,1), (1,0), (1,1)]:
        start_scope()

        # Layer 1
        layer1_eqs = '''
        dv/dt = (I - v)/tau : 1
        I : 1
        '''
        layer1 = NeuronGroup(2, layer1_eqs, threshold='v > V_th_layer1', reset='v = V_reset', method='exact')
        layer1.I = [weights_layer1[0][0]*A + weights_layer1[0][1]*B,
                    weights_layer1[1][0]*A + weights_layer1[1][1]*B]

        # Layer 2 (OR)
        layer2 = NeuronGroup(1, layer1_eqs, threshold='v > V_th_layer2', reset='v = V_reset', method='exact')
        syn = Synapses(layer1, layer2, 'w : 1', on_pre='v_post += w')
        syn.connect(i=0, j=0); syn.w[0] = 1.0
        syn.connect(i=1, j=0); syn.w[1] = 1.0

        spike_mon = SpikeMonitor(layer2)
        run(20*ms)
        print(f"Input ({A},{B}) → Output: {1 if spike_mon.count[0] > 0 else 0}")

# =============================================================================
# Run All Simulations
# =============================================================================
simulate_AND()
simulate_OR()
simulate_NOT()
simulate_XOR()

!pip install brian2 matplotlib numpy --quiet
from brian2 import *
import matplotlib.pyplot as plt
import numpy as np

# =============================================================================
# 1. Core LIF Gate Implementations
# =============================================================================
def simulate_gate(gate_type, inputs, weights, threshold, runtime=30*ms):
    """Simulate LIF logic gate and plot membrane potential with spike indication."""
    print(f"\n{gate_type} Gate Results:")

    for inp in inputs:
        start_scope()

        # Define neuron group
        neuron = NeuronGroup(1,
            '''dv/dt = (I - v)/(10*ms) : 1
               I : 1 (shared)''',
            threshold=f'v > {threshold}',
            reset='v = 0',
            method='exact')

        # Assign input current
        if gate_type == 'NOT':
            A = inp
            neuron.I = weights[0]*A + weights[1]  # w_A*A + bias
        else:
            A, B = inp
            neuron.I = weights[0]*A + weights[1]*B

        # Monitors
        state_mon = StateMonitor(neuron, 'v', record=True)
        spike_mon = SpikeMonitor(neuron)

        # Run simulation
        net = Network(neuron, state_mon, spike_mon)
        net.run(runtime)

        # Determine output
        output = 1 if spike_mon.count[0] > 0 else 0
        print(f"Input {inp} → Output: {output}")

        # Plotting
        plt.figure(figsize=(4, 3))
        plt.plot(state_mon.t / ms, state_mon.v[0], label='Membrane Potential')
        plt.axhline(threshold, color='red', linestyle='--', label='Threshold')

        # Optional: mark spike times
        if spike_mon.count[0] > 0:
            for t in spike_mon.t:
                plt.axvline(t/ms, color='green', linestyle=':', label='Spike')

        plt.title(f'{gate_type} Gate: Input {inp} → Output: {output}')
        plt.xlabel('Time (ms)')
        plt.ylabel('Voltage')
        plt.legend()
        plt.tight_layout()
        plt.savefig(f'{gate_type}_input_{inp}.png', dpi=120)
        plt.close()


# =============================================================================
# 2. XOR Network Implementation
# =============================================================================
def simulate_XOR():
    print("\nXOR Gate Results:")
    inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]

    for A, B in inputs:
        start_scope()

        # ---------------------
        # Layer 1: Hidden Neurons
        # ---------------------
        layer1_eqs = '''
        dv/dt = (I - v)/(10*ms) : 1
        I : 1
        '''
        layer1 = NeuronGroup(2, layer1_eqs,
                             threshold='v > 1.0',
                             reset='v = 0',
                             method='exact')
        # Weighted current injection for A∧¬B and ¬A∧B
        layer1.I = [2.0*A - 2.0*B, -2.0*A + 2.0*B]

        # ---------------------
        # Layer 2: Output Neuron (OR of Layer 1)
        # ---------------------
        layer2_eqs = '''
        dv/dt = (I - v)/(10*ms) : 1
        I : 1
        '''
        layer2 = NeuronGroup(1, layer2_eqs,
                             threshold='v > 0.9',
                             reset='v = 0',
                             refractory=5*ms,
                             method='exact')

        # Synapse: Current-based summation from both layer1 neurons
        syn = Synapses(layer1, layer2,
                       'w : 1',
                       on_pre='I_post += w')
        syn.connect(i=[0, 1], j=0)
        syn.w = [1.5, 1.5]  # Boosted weights for reliable firing

        # ---------------------
        # Monitors
        # ---------------------
        m1 = StateMonitor(layer1, 'v', record=True)
        m2 = StateMonitor(layer2, 'v', record=True)
        spike_mon_layer2 = SpikeMonitor(layer2)

        # ---------------------
        # Run simulation
        # ---------------------
        net = Network(layer1, layer2, syn, m1, m2, spike_mon_layer2)
        net.run(25*ms)  # Slightly longer to allow late spikes

        # ---------------------
        # Output and Plot
        # ---------------------
        output = 1 if spike_mon_layer2.count[0] > 0 else 0
        print(f"Input ({A},{B}) → Output: {output}")

        # Plotting
        plt.figure(figsize=(8, 4))
        plt.plot(m1.t/ms, m1.v[0], label='Neuron 1 (A∧¬B)')
        plt.plot(m1.t/ms, m1.v[1], label='Neuron 2 (¬A∧B)')
        plt.plot(m2.t/ms, m2.v[0], 'k--', label='Output Neuron')
        plt.axhline(0.9, color='r', linestyle=':', label='Threshold')
        plt.title(f'XOR Gate: Input ({A},{B})')
        plt.xlabel('Time (ms)')
        plt.ylabel('Membrane Potential')
        plt.legend()
        plt.tight_layout()
        plt.savefig(f'XOR_{A}_{B}.png', dpi=150)
        plt.close()




# =============================================================================

# =============================================================================
# 3. Hardware Schematic Generation
# =============================================================================
def generate_hardware_schematic():
    """Generate neuromorphic circuit diagram"""
    fig, ax = plt.subplots(figsize=(10, 4))

    # Neurons
    ax.add_patch(plt.Circle((0.2, 0.5), 0.05, color='blue', label='LIF Neuron'))
    ax.add_patch(plt.Circle((0.8, 0.5), 0.05, color='blue'))

    # Synapses
    ax.plot([0.25, 0.75], [0.5, 0.5], 'gray', lw=2, label='Synapse')

    # Inputs/Outputs
    ax.text(0.1, 0.5, 'Input A\nInput B', ha='right', va='center')
    ax.text(0.9, 0.5, 'Output', ha='left', va='center')

    plt.title('Neuromorphic Hardware Implementation', pad=20)
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.axis('off')
    plt.legend(loc='upper center', ncol=2)
    plt.savefig('hardware_schematic.png', dpi=200, bbox_inches='tight')
    plt.close()

# =============================================================================
# 4. Main Execution
# =============================================================================
if __name__ == "__main__":
    # AND Gate
    simulate_gate('AND',
                 inputs=[(0,0), (0,1), (1,0), (1,1)],
                 weights=[1.0, 1.0],  # w_A, w_B
                 threshold=1.5)

    # OR Gate
    simulate_gate('OR',
                 inputs=[(0,0), (0,1), (1,0), (1,1)],
                 weights=[1.0, 1.0],
                 threshold=0.8)  # Adjusted from 0.9

    # NOT Gate
    simulate_gate('NOT',
                 inputs=[0, 1],
                 weights=[-1.0, 1.0],  # w_A, bias
                 threshold=0.5)

    # XOR Gate
    simulate_XOR()

    # Hardware Diagram
    generate_hardware_schematic()

    print("\nAll simulations completed! Check generated PNG files.")